services:
  postgres:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ecommerce_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  indora-api:
    image: yanvelasco/indora-api:v1
    container_name: indora-api
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/ecommerce_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: